version: '3'

tasks:
  test:
    cmds:
      - go test -covermode=atomic -race -tags=test_helpers -coverprofile=coverage.txt -timeout 5m -json -v ./... | gotestfmt -showteststatus
  cli-tools:
    cmds:
      - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
      - go install github.com/ramya-rao-a/go-outline@latest
      - go install github.com/cweill/gotests/gotests@latest
      - go install github.com/fatih/gomodifytags@latest
      - go install github.com/josharian/impl@latest
      - go install github.com/haya14busa/goplay/cmd/goplay@latest
      - go install github.com/go-delve/delve/cmd/dlv@latest
      - go install mvdan.cc/gofumpt@latest
      - go install github.com/cosmtrek/air@latest
  fmt:
    cmds:
      - gofumpt -l -w .
  lint:
    cmds:
      - golangci-lint run
  sec:
    cmds:
      - gosec ./...
  tidy:
    cmds:
      - rm -f go.sum
      - go mod tidy
