name: 'Testing'

on:
  workflow_call:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: [1.19]
    runs-on: ${{ matrix.os }}
    container: golang:${{ matrix.go }}-bullseye
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Test ${{ matrix.go }}
        run: |
          make RACE=1 test
