name: 'Testing'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go: ['1.21']
    runs-on: ${{ matrix.os }}
    container: golang:${{ matrix.go }}-bullseye
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
          cp config.example.yml config.yml
          task test
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt
          flags: unit-tests
          name: codecov-umbrella
          fail_ci_if_error: false
          verbose: false